# This yaml file contains parameters for hmm.py
# Paths are relative to the location of this config file.
# All arguments provided here can be overriden by command line arguments

# CSV file containing the input telemetry data.
input:          '../data/2020-35_2/2020-35_2-last-20.csv'

# CSV file containing the output telemetry data subset. Defaults to './subset.csv'.
output:         '../graphs'

num-states: 2

turning-angle: False

speed: True

depth: False