# This yaml file contains parameters for hmm.py
# Paths are relative to the location of this config file.
# All arguments provided here can be overriden by command line arguments

# CSV file containing the input telemetry data.
input:          '../data/2020-21/runs/207-long-3-min.csv'

# output directory
output:         '../models'

num-states: 2

observation-types: ['turning_angle', 'speed']

covariate-types: ['temperature']