# This yaml file contains parameters for subset.py
# Paths are relative to the location of this config file.
# All arguments provided here can be overriden by command line arguments

# CSV file containing the input telemetry data.
input:          '../data/SharkArray-01.csv'

# CSV file containing the output telemetry data subset. Defaults to './subset.csv'.
output:         '../data/SharkArray-2020-05-21.csv'

# Start time for the time range to filter the data by. Leave blank or set to 'None' to not filter by start time. Defaults to '2020-05-21 00:00:00'.
start-time:     '2020-05-21 00:00:00'

# End time for the time range to filter the data by. Leave blank or set to 'None' to not filter by end time. Defaults to '2020-05-22 00:00:00'.
end-time:       '2020-05-22 00:00:00'

# List of ids to filter the data by. Defaults to ['2020-20'].
id-list:
    ['Ref01',
     'Off_A',
     'In_B',
     'Off_E',
     'In_D',
     'In_F',
     'Off_C',
     'Off_G',
     'In_A',
     'In_G']

# Mode for filtering by id. Include mode keeps only the ids given for id-list, while exlcude mode keeps all the others. Defaults to 'include'.
id-filter-mode: 'exclude'